[project]
name = "vehicleroute"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopy>=2.4.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pyqt6>=6.10.1",
    "pyyaml>=6.0.3",
]
